export type FlockStackParamList = {
  FlockHome: undefined;
  BirdProfile: { birdId: number };
  AddEditBird: { birdId?: number };
  AddEditFlock: { flockId?: number };
  HealthRecordDetail: { recordId: number };
  AddEditHealthRecord: { birdId: number; recordId?: number };
  EggDashboard: undefined;
  EggHistory: undefined;
  AddEditEggRecord: { recordId?: number };
  FeedInventory: undefined;
  AddEditFeedItem: { itemId?: number };
  LogFeedUsage: { feedItemId?: number; logId?: number };
  FeedHistory: undefined;
  BreedingHub: undefined;
  BreedingPairList: undefined;
  AddEditBreedingPair: { pairId?: number };
  ClutchHistory: undefined;
  AddEditClutch: { clutchId?: number };
  ClutchDetail: { clutchId: number };
  AddEditCandlingRecord: { clutchId: number; recordId?: number };
  AddEditHatchRecord: { clutchId: number };
  CreateBirdsFromHatch: { hatchRecordId: number };
};
